### ISSUE TITLE
feat(processor): bibliography title

### ISSUE THREAD

**Issue by richlewis42** [richlewis42/simple-cite#1]
Optionally add title to bibliography, e.g.:

### Text

```text
References

1. Bloggs, J. (2016). Item A.
...
```
### HTML

```html
<div class="csl-bib-body">
  <h2>References</h2>
  <div class="csl-entry">Bloggs, J. (2016). Item A.</div>
  ...
</div>
```

- [x] use optional arg in `Processor.prototype.bibliography`
- [ ] allow html heading level to be set?
- [x] use locale to get relevant name (use term "reference")

**Comment by lewisacidic** [comment]
Added in 138de3d
